In [1]:
#Felipe Borges - 2111351 - Lista 3
#Github - https://github.com/Borgeszz/Lista3.git

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

breast_cancer = pd.read_csv('/content/drive/MyDrive/class_breast_cancer.csv')

breast_cancer = pd.DataFrame(breast_cancer)

display(breast_cancer)

Mounted at /content/drive

,ID,radius,texture,perimeter,area,smoothness,compacity,concavity,pts_concavity,symmetry,...,minor_texture,minor_perimeter,minor_area,minor_smoothness,minor_compacity,minor_concavity,minor_pts_concavity,minor_symmetry,minor_fractal,target
0,842302,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,M
1,842517,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,M
2,84300903,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,M
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,M
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,M
565,926682,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,M
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,M
567,927241,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,M
568,92751,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,B

In [2]:
#Inspecione as colunas do conjunto de dados (Nome das colunas e tipo de dados)

breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   569 non-null    int64
 1   radius               569 non-null    float64
 2   texture              569 non-null    float64
 3   perimeter            569 non-null    float64
 4   area                 569 non-null    float64
 5   smoothness           569 non-null    float64
 6   compacity            569 non-null    float64
 7   concavity            569 non-null    float64
 8   pts_concavity        569 non-null    float64
 9   symmetry             569 non-null    float64
 10  fractal              569 non-null    float64
 11  std_radius           569 non-null    float64
 12  std_texture          569 non-null    float64
 13  std_perimeter        569 non-null    float64
 14  std_area             569 non-null    float64
 15  std_smoothness       569 non-null    float64
 16  std_compacity        569 non-null    float64
 17  std_concavity        569 non-null    float64
 18  std_pts_concavity    569 non-null    float64
 19  std_symmetry         569 non-null    float64
 20  std_fractal          569 non-null    float64
 21  minor_radius         569 non-null    float64
 22  minor_texture        569 non-null    float64
 23  minor_perimeter      569 non-null    float64
 24  minor_area           569 non-null    float64
 25  minor_smoothness     569 non-null    float64
 26  minor_compacity      569 non-null    float64
 27  minor_concavity      569 non-null    float64
 28  minor_pts_concavity  569 non-null    float64
 29  minor_symmetry       569 non-null    float64
 30  minor_fractal        569 non-null    float64
 31  target               569 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [3]:
#Escolha uma coluna com valores numéricos e apague todas as linhas que possuam valor nulo

breast_cancer['concavity'] = breast_cancer['concavity'].replace(0,np.nan)

breast_cancer['concavity'] = breast_cancer['concavity'].dropna()

In [4]:
#Calcule a média desta mesma coluna

med = breast_cancer['concavity'].mean()
print(med)

0.09087555881294963

In [5]:
#Escolha um critério para eliminar as linhas que possuam valores muito distantes da média e crie um novo Dataframe.

crit1 = breast_cancer['concavity'] >=0.01
crit2 = breast_cancer['concavity'] <=0.3

breast_cancer = breast_cancer[crit1]
breast_cancer = breast_cancer[crit2]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys

In [6]:
#Crie um novo Dataframe que contenha apenas 5 colunas do conjunto anterior.

breast_cancer2 = breast_cancer.drop(['radius','texture','perimeter','area','smoothness'],axis=1)

In [7]:
#Escolha duas colunas numéricas e crie uma nova coluna que siga a regra: (Coluna A - Coluna B)*número aleatório (entre 0 e 1).

breast_cancer2['coluna_nova'] = breast_cancer2['compacity']-breast_cancer2['fractal']
breast_cancer2['coluna_nova'] = breast_cancer2['coluna_nova']*0.4

In [8]:
#Embaralhe aleatoriamente o dataframe (índices e valores).

breast_cancer_random = breast_cancer2.sample(frac=1)

In [9]:
#Ordene o Dataframe seguindo um critério definido por você (Explique o critério)

breast_cancer2 = breast_cancer2[['fractal','compacity','symmetry','coluna_nova','target']] #Organizei de maneira aleatoria, sem nenhum criterio especifico
breast_cancer2.sort_values(by = ['symmetry']).reset_index(drop=True) #Organizei a coluna da simetria em ordem crescente, depois resetei o index para ficar de acordo com a nova ordem

     fractal  compacity  symmetry  coluna_nova target
0    0.06217    0.08155    0.1167     0.007752      B
1    0.06659    0.10730    0.1203     0.016284      B
2    0.05243    0.06217    0.1220     0.003896      B
3    0.06724    0.06053    0.1274    -0.002684      B
4    0.07163    0.12430    0.1305     0.021068      B
..       ...        ...       ...          ...    ...
506  0.06233    0.11810    0.2595     0.022308      B
507  0.09744    0.28390    0.2597     0.074584      M
508  0.07371    0.17000    0.2678     0.038516      M
509  0.06960    0.08061    0.2743     0.004404      B
510  0.07413    0.22760    0.3040     0.061388      M

[511 rows x 5 columns]

In [16]:
#Escolha uma coluna numérica e um coluna com strings e utilize a função Groupby para mostrar os totais da coluna.

junçao = breast_cancer2.groupby(['compacity','target']).count()

In [17]:
#Utilize a função MAPS para fazer algum tipo de substituição no Dataframe (explique)

breast_cancer2['target'] = breast_cancer2['target'].map({'M':'Metastasis','B':'Luminal B'}) #Usei a funcao MAPS e troquei o nome dos estagios do cancer de mama

In [13]:
#Exporte o último Dataframe para um arquivo CSV 

breast_cancer2.to_csv('/content/drive/MyDrive/breast_cancer.csv')

In [14]:
#Exporte o último Dataframe para um arquivo JSON 

breast_cancer2.to_json('/content/drive/MyDrive/breast_cancer.json')